# Generated by Django 2.2.4 on 2019-09-08 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20190908_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator.__call__]),
        ),
        migrations.AlterField(
            model_name='place',
            name='types',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator.__call__]),
        ),
    ]
