# Generated by Django 2.2.4 on 2019-09-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
