# Generated by Django 2.2.4 on 2019-09-03 06:47

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventtiming',
            constraint=models.CheckConstraint(check=models.Q(start_time__lt=django.db.models.expressions.F('end_time')), name='valid_time_interval'),
        ),
    ]
