# Generated by Django 2.2.4 on 2019-09-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190903_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='eventtiming',
            options={'ordering': ('start_time', 'end_time')},
        ),
    ]
