# Generated by Django 2.2.4 on 2019-09-09 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('asin', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter valid phone number', regex='^\\d+$')])),
                ('release_date', models.DateField()),
                ('cover', models.ImageField(upload_to='musics')),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BandMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('instrument', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter valid phone number', regex='^\\+\\d{1,3}-\\d{3,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musics', to='musics.Album')),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musics', to='musics.Band')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(related_name='bands', to='musics.BandMembers'),
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums_band', to='musics.Band'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(related_name='albums', to='musics.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums_label', to='musics.Band'),
        ),
        migrations.AddConstraint(
            model_name='music',
            constraint=models.UniqueConstraint(fields=('title', 'album'), name='unique_music_title'),
        ),
        migrations.AddConstraint(
            model_name='music',
            constraint=models.UniqueConstraint(fields=('slug', 'album'), name='unique_music_slug'),
        ),
    ]
