# Generated by Django 2.2.4 on 2019-09-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BandMembers',
            new_name='BandMember',
        ),
    ]
