# Generated by Django 2.2.4 on 2019-09-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20190909_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(unique=True, upload_to='musics'),
        ),
    ]
