# Generated by Django 2.2.4 on 2019-09-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_auto_20190909_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='musics.Band'),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='musics.Label'),
        ),
    ]
