# Generated by Django 2.2.4 on 2019-09-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_auto_20190909_0813'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='music',
            name='unique_music_title',
        ),
        migrations.RemoveConstraint(
            model_name='music',
            name='unique_music_slug',
        ),
        migrations.AlterField(
            model_name='music',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
