# Generated by Django 2.2.4 on 2019-09-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_auto_20190909_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='members',
        ),
        migrations.DeleteModel(
            name='BandMember',
        ),
    ]
