# Generated by Django 2.2.4 on 2019-09-08 10:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter valid phone number', regex='^\\+\\d{1,3}-\\d{3,15}$')])),
                ('birth_date', models.DateField()),
                ('website', models.URLField(unique=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female')])),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('website', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('sub_title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('released_date', models.DateField()),
                ('cover_image', models.ImageField(unique=True, upload_to='movies')),
                ('review', models.FloatField(default=5)),
                ('asin', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter valid phone number', regex='^\\d+$')])),
                ('directors', models.ManyToManyField(related_name='movies', to='movies.Director')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.Studio')),
            ],
        ),
    ]
